name: publish
on: [push]
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Test
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the hello-docker Docker image
      run: |
        docker build . --tag ghcr.io/owenvanrijn/test-repo-idk:latest
        docker push ghcr.io/owenvanrijn/test-repo-idk:latest
